# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts
  
variables:
  buildConfiguration: 'Release'
  anotherVariable: 'me'

jobs:
- job: a
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
      dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

  - task: PublishBuildArtifacts@1

- job: b
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
      dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

  - task: PublishBuildArtifacts@1

